LOCAL_PATH := device/smartisan/sm705

# Architecture
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := krait
TARGET_USE_QCOM_BIONIC_OPTIMIZATION := true
TARGET_BOARD_PLATFORM := msm8974
TARGET_USES_QCOM_BSP := true
BOARD_USES_QCOM_HARDWARE := true

TARGET_POWERHAL_VARIANT := qcom
TARGET_QCOM_MEDIA_VARIANT := caf

TARGET_CPU_SMP := true
TARGET_BOOTLOADER_BOARD_NAME := msm8974sfo-lte
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

# Kernel
BOARD_KERNEL_CMDLINE := androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0xbf ehci-hcd.park=3
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048
#BOARD_KERNEL_SEPARATED_DT := true
#TARGET_KERNEL_APPEND_DTB := true
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x01000000 --tags_offset 0x00000100 --dt $(LOCAL_PATH)/dt
#TARGET_PREBUILT_KERNEL := $(LOCAL_PATH)/zImage
#TARGET_BOARD_KERNEL_HEADERS := $(LOCAL_PATH)/kernel-headers
TARGET_KERNEL_SOURCE := kernel/smartisan/t1
TARGET_KERNEL_CONFIG := msm8974sfo-lte_defconfig
BOARD_KERNEL_IMAGE_NAME := zImage

# Partition size
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1388314624
BOARD_USERDATAIMAGE_PARTITION_SIZE := 28891414528
BOARD_FLASH_BLOCK_SIZE := 131072

# Recovery
TARGET_RECOVERY_FSTAB := $(LOCAL_PATH)/recovery.fstab
RECOVERY_FSTAB_VERSION := 2
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_23x41.h\"
BOARD_HAS_NO_SELECT_BUTTON := true
DEVICE_RESOLUTION := 1920x1080
TARGET_OTA_ASSERT_DEVICE := msm8974sfo,msm8974sfo-lte,sm705
BOARD_CHARGER_ENABLE_SUSPEND := true

#Graphics
TARGET_QCOM_DISPLAY_VARIANT := caf
OVERRIDE_RS_DRIVER := libRSDriver_adreno.so
HAVE_ADRENO_SOURCE:= false
MAX_EGL_CACHE_KEY_SIZE := 12*1024
MAX_EGL_CACHE_SIZE := 2048*1024
TARGET_USES_ION := true
TARGET_USES_C2D_COMPOSITION := true
TARGET_USES_POST_PROCESSING := true
USE_OPENGL_RENDERER := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
VSYNC_EVENT_PHASE_OFFSET_NS := 7500000
SF_VSYNC_EVENT_PHASE_OFFSET_NS := 5000000
BOARD_EGL_CFG := $(LOCAL_PATH)/egl.cfg
#TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
#TARGET_DISPLAY_USE_RETIRE_FENCE := true

# Time services
BOARD_USES_QC_TIME_SERVICES := true

#Audio
#TARGET_QCOM_AUDIO_VARIANT := caf
BOARD_USES_ALSA_AUDIO := true

# Wifi
#BOARD_HAS_QCOM_WLAN              := true
#BOARD_WLAN_DEVICE                := qcwcn
#WPA_SUPPLICANT_VERSION           := VER_0_8_X
#BOARD_WPA_SUPPLICANT_DRIVER      := NL80211
#BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_$(BOARD_WLAN_DEVICE)
#BOARD_HOSTAPD_DRIVER             := NL80211
#BOARD_HOSTAPD_PRIVATE_LIB        := lib_driver_cmd_$(BOARD_WLAN_DEVICE)
#WIFI_DRIVER_FW_PATH_STA          := "sta"
#WIFI_DRIVER_FW_PATH_AP           := "ap"
#WIFI_DRIVER_MODULE_PATH          := "/system/lib/modules/wlan.ko"
#WIFI_DRIVER_MODULE_NAME          := "wlan"

#Bluetooth
BOARD_HAVE_BLUETOOTH := true

BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := $(TARGET_BOARD_PLATFORM)
TARGET_NO_RPC := true
